apiVersion: v1
kind: Deployment
metadata:
  name: deploy-nginx
  labels:
    app: nginx
spec:
  template:
    metadata:
      name: nginx
      labels:
        app: 
    spec:
      containers:
        - name: nginx
          image: nginx:1.22
  selector:
    matchLabels:
      app: 
  replicas: 4